DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tasks;


CREATE TABLE users(
id SERIAL PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE tasks(
id SERIAL PRIMARY KEY,
title TEXT NOT NULL,
done BOOLEAN DEFAULT false NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL);